config/routes.rb
Rails.application.routes.draw do
  get 'profiles/new'
  devise_for :users
  root to: 'pages#home'
  resources :profiles, except: [:edit]
  get 'fetch_nickname', to: "profiles#fetch_nickname"
  get 'fetch_origin_story', to: "profiles#fetch_origin_story"
  resources :chosen_visions, only: [:create, :update]
  resources :chosen_strategies, only: [:create, :update]
  resources :bad_guys, only: [:create, :update]
  resources :quests, only: [:create, :update]
  resources :power_ups, only: [:create, :update]
  get 'adventures', to: "pages#adventure", as: :adventure
  get 'profile', to: "profiles#new", as: :main_profile

  resources :dashboard, only: :index
  patch "defeat_bad_guy/:id", to: "dashboard#defeat_bad_guy", as: :defeat_bad_guy
  patch "increase_power_up/:id", to: "dashboard#increase_power_up", as: :increase_power_up
  post "change_completion_rate", to: "dashboard#change_completion_rate", as: :change_completion_rate
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad_guy.rb
class BadGuy < ApplicationRecord
  belongs_to :profile
  validates :name, presence: true, uniqueness: { scope: :profile }
  validates :story, presence: true
  validates :xp, presence: true
end

app/models/chosen_strategy.rb
class ChosenStrategy < ApplicationRecord
  belongs_to :profile
  belongs_to :strategy

  has_many :quest_strategies
  has_many :quests, through: :quest_strategies
end

app/models/chosen_vision.rb
class ChosenVision < ApplicationRecord
  belongs_to :profile
  belongs_to :vision

  has_many :power_up_visions
  has_many :power_ups, through: :power_up_visions

  validates :motto, presence: true

end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_one :vision
  has_many :strategies
  has_many :company_bad_guys
  has_many :company_quests
  has_many :company_power_ups

  validates :name, presence: true
end

app/models/company_bad_guy.rb
class CompanyBadGuy < ApplicationRecord
  belongs_to :company
end

app/models/company_power_up.rb
class CompanyPowerUp < ApplicationRecord
  belongs_to :company
end

app/models/company_quest.rb
class CompanyQuest < ApplicationRecord
  belongs_to :company
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/power_up.rb
class PowerUp < ApplicationRecord
  belongs_to :profile

  validates :name, presence: true, uniqueness: { scope: :profile }
  validates :description, presence: true
  validates :xp, presence: true
end

app/models/power_up_vision.rb
class PowerUpVision < ApplicationRecord
  belongs_to :chosen_vision
  belongs_to :power_up
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_one :chosen_vision
  has_many :bad_guys, through: :profile

  has_many :chosen_strategies
  has_many :quests
  has_many :bad_guys
  has_many :power_ups

  validates :nickname, presence: true
  validates :secret_bio, presence: true
  ORIGIN_STORIES = [
    "$NICKNAME had parents murdered by one of the muggers when he was young while walking home from the movies with their parents. Later discovered that their city was plagued by corrupt officials, inspired them to used their vast family fortune to become $NICKNAME and wage a one-person war on crime.",
    "Born on the planet Krypton, infant $NICKNAME was sent to Earth before an explosion destroyed their home planet. Their strong moral code motivates them to fight for justice.",
    "$NICKNAME was once an ordinariy human child, having scientist parents that injected them with reverse evolution serum to save their life from a deadly virus which led to the start of their superhero career.",
    "$NICKNAME was once either an intermediate dinosaur or a prehistoric intermediate reptile who was later transformed into a giant monster by the nuclear test that damaged their original home",
    "Originally an orphaned cat. They both stole different types of beans in the search of the magic beans. After some time, $NICKNAME gave up stealing things. But their crime buddies, unable to steal without the cat's help, tricked them into a bank robbery. From then on, $NICKNAME became a fugitive from law, searching a way to clear their name",
    "$NICKNAME, a Saiyan baby was sent from Planet Vegeta to Earth to destroy it, but ended up having a nasty bump on the head, which causes them to completely lose their Saiyan characteristics and become an Earthling.",
    "$NICKNAME was the chosen one to fight all that is evil, although they were separated from their parents during war. For a brief period of time, they went down to a darker path until eventually choose to redeem themselves, starting their adventures as a hero.",
    "Originally, Officer Sam Weathers was killed in the line of duty and brought back to life as a crime-fighting cyborg called $NICKNAME"
  ]

  def current_quests
    self.quests.where(completed: false)
  end

  def completed_quests
    self.quests.where(completed: true)
  end

  def completed_quests_xp
    completed_quests.sum(&:xp)
  end

  def bad_guys_xp
    bad_guys.sum(&:total_xp)
  end

  def total_power_ups_xp
    power_ups.sum(&:total_xp)
  end

  def total_xp
    return completed_quests_xp + bad_guys_xp + total_power_ups_xp || 0
  end

  def self.get_random_story(nickname)
    ORIGIN_STORIES.sample.gsub("$NICKNAME", nickname)
  end

end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :profile
  has_many :quest_strategies
  has_many :chosen_strategies, through: :quest_strategies
  accepts_nested_attributes_for :quest_strategies

  validates :name, presence: true
  validates :completion_rate, presence: true
  validates :description, presence: true
  validates :xp, presence: true
end

app/models/quest_strategy.rb
class QuestStrategy < ApplicationRecord
  belongs_to :quest
  belongs_to :chosen_strategy
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  belongs_to :company
  has_many :chosen_strategies
  has_many :profiles, through: :chosen_strategies

  validates :name, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :company
  has_one :profile
  before_validation :assign_company
  has_many :memberships
  has_many :teams, through: :memberships

  private

  def assign_company
    self.company ||= Company.last
  end
end

app/models/vision.rb
class Vision < ApplicationRecord
  belongs_to :company
  has_many :chosen_visions
  has_many :profiles, through: :chosen_visions

  validates :name, presence: true
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @current_quests = current_user.profile.current_quests.order(:created_at)
    @completed_quests = current_user.profile.completed_quests

    @power_ups = current_user.profile.power_ups
    @bad_guys = current_user.profile.bad_guys

    @teams = current_user.teams
    # @allies = current_user.allies
    @chosen_strategies = current_user.profile.chosen_strategies
  end

  def defeat_bad_guy
    bad_guy = BadGuy.find(params[:id])
    bad_guy.total_xp += bad_guy.xp
    bad_guy.save!
    redirect_to dashboard_index_path(anchor: "bad-guy-#{bad_guy.id}")
  end

  def increase_power_up
    power_up = PowerUp.find(params[:id])
    power_up.total_xp += power_up.xp
    power_up.save!
    redirect_to dashboard_index_path(anchor: "power-up-#{power_up.id}")
  end

  def change_completion_rate
    @quest = Quest.find(params["quest"]["id"])
    @quest.completion_rate = params["quest"]["completion_rate"].to_i
    @quest.completed = true if @quest.completion_rate == 100
    @quest.save!
    flash[:notice] = "Updated !"
    redirect_to dashboard_index_path(anchor: "quest-#{@quest.id}")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def adventure
    @new_bad_guy = BadGuy.new
    @new_power_up = PowerUp.new
    @new_quest = Quest.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_active_quest.html.erb
<div data-controller="quest" class="card mb-5 p-2 w-100" id="quest-<%= quest.id %>">
  <h3><strong><%= quest.name.capitalize %></strong></h3>
  <p class="text-muted"><%= quest.description %></p>
  <div class="d-flex w-100 justify-content-between">
    <p>Reward: <strong><%= quest.xp %> XP </strong></p>
    <% if quest.chosen_strategies.present? %>
      <div class="dropdown">
        <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="quest_dropdown_<%= quest.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            see associated strategies
        </button>
        <div class="dropdown-menu" aria-labelledby="quest_dropdown_<%= quest.id %>">
          <% quest.chosen_strategies.each do |strategy| %>
            <p class="text-small text-muted m-1"> <%= strategy.personal_strategic_goal %> </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% if params[:controller] == "dashboard" %>
    <%= simple_form_for quest, as: :quest, url: change_completion_rate_path, method: :post,  remote: true do |f| %>
      <%= f.input :id, as: :hidden %>
      <%= f.input :completion_rate, label: " <span data-quest-target='text'>Completion rate: #{quest.completion_rate} %</>".html_safe, as: :range, min: 0, max: 100, input_html: {data: { action: "change->quest#slide"}} %>
      <%= f.button :submit, class: "btn btn-info d-none", data: { target: "quest.submit"}  %>
    <% end %>
  <% end %>

</div>

app/views/dashboard/_bad_guy.html.erb
<div class="card mb-5 p-2 w-100" id="bad-guy-<%= bad_guy.id %>" >
  <h3><strong><%= bad_guy.name.capitalize %></strong></h3>
  <p class="text-muted"><%= bad_guy.story %></p>
  <p>Total XP gained from previously slaying this baddie: <strong><%= bad_guy.total_xp %> XP </strong></p>
  <p>Reward: <%= bad_guy.xp %> XP</p>
  <% if params[:controller] == "dashboard" %>
    <%= link_to "Neutralized!", defeat_bad_guy_path(bad_guy), method: :patch, class: "btn btn-info", remote: true  %>
  <% end %>
</div>

app/views/dashboard/_completed_quest.erb
<div class="card mb-5 p-2 w-100" id="quest-<%= quest.id %>">
  <h3><s><strong><%= quest.name.capitalize %></strong></s></h3>
  <p class="text-muted"><%= quest.description %></p>
  <div class="d-flex w-100 justify-content-between">
    <p>Received: <strong> <%= quest.xp %> XP </strong></p>
    <% if quest.chosen_strategies.present? %>
      <div class="dropdown">
        <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="quest_dropdown_<%= quest.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            see associated strategies
        </button>
        <div class="dropdown-menu" aria-labelledby="quest_dropdown_<%= quest.id %>">
          <% quest.chosen_strategies.each do |strategy| %>
            <p class="text-small text-muted m-1"> <%= strategy.personal_strategic_goal %> </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/_power_up.html.erb
<div class="card mb-5 p-2 w-100" id="power-up-<%= power_up.id %>">
  <h3><strong><%= power_up.name.capitalize %></strong></h3>
  <p class="text-muted"><%= power_up.description %></p>
  <p>Total XP gained from previously slaying this PowerUp: <strong> <%= power_up.total_xp %> XP </strong></p>
  <p>Reward: <%= power_up.xp %> XP</p>
  <% if params[:controller] == "dashboard" %>
    <%= link_to "Acquire PowerUp!", increase_power_up_path(power_up), method: :patch, class: "btn btn-info", remote: true %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container d-flex flex-column align-items-center">
  <h1>My Dashboard</h1>

    <div class="row">

      <div class="col d-flex flex-column">
        <h2>📝 Active Quests 📝</h2>
        <% @current_quests.each do |current_quest| %>
          <%= render "active_quest", quest: current_quest %>
        <% end %>
      </div>

      <div class="col d-flex flex-column">
        <h2>✔ Completed Quests ✔</h2>
        <% @completed_quests.each do |completed_quest| %>
          <%= render "completed_quest", quest: completed_quest %>
        <% end %>
      </div>

    </div>

  <div class="row">

    <div class="col d-flex flex-column align-items-center">
      <h2>⭐ Power Ups! ⭐</h2>
      <% @power_ups.each do |power_up| %>
        <%= render "power_up", power_up: power_up %>
      <% end %>
    </div>

    <div class="col d-flex flex-column align-items-center">
      <h2>🤠 Most Wanted Baddies 🤠</h2>
      <% @bad_guys.each do |bad_guy| %>
       <%= render "bad_guy", bad_guy: bad_guy %>
      <% end %>
    </div>

  </div>

</div>