config/routes.rb
Rails.application.routes.draw do
  get 'profiles/new'
  devise_for :users
  root to: 'pages#home'
  resources :profiles, except: [:edit]
  get 'fetch_nickname', to: "profiles#fetch_nickname"
  get 'fetch_origin_story', to: "profiles#fetch_origin_story"
  resources :chosen_visions, only: [:create, :update]
  resources :chosen_strategies, only: [:create, :update]
  resources :bad_guys, only: [:create, :update]
  resources :quests, only: [:create, :update]
  resources :power_ups, only: [:create, :update]
  get 'adventures', to: "pages#adventure", as: :adventure
  get 'profile', to: "profiles#new", as: :main_profile

  resources :dashboard, only: :index
  patch "defeat_bad_guy/:id", to: "dashboard#defeat_bad_guy", as: :defeat_bad_guy
  patch "increase_power_up/:id", to: "dashboard#increase_power_up", as: :increase_power_up
  post "change_completion_rate", to: "dashboard#change_completion_rate", as: :change_completion_rate
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_one :chosen_vision
  has_many :bad_guys, through: :profile

  has_many :chosen_strategies
  has_many :quests
  has_many :bad_guys
  has_many :power_ups

  validates :nickname, presence: true
  validates :secret_bio, presence: true
  ORIGIN_STORIES = [
    "$NICKNAME had parents murdered by one of the muggers when he was young while walking home from the movies with their parents. Later discovered that their city was plagued by corrupt officials, inspired them to used their vast family fortune to become $NICKNAME and wage a one-person war on crime.",
    "Born on the planet Krypton, infant $NICKNAME was sent to Earth before an explosion destroyed their home planet. Their strong moral code motivates them to fight for justice.",
    "$NICKNAME was once an ordinariy human child, having scientist parents that injected them with reverse evolution serum to save their life from a deadly virus which led to the start of their superhero career.",
    "$NICKNAME was once either an intermediate dinosaur or a prehistoric intermediate reptile who was later transformed into a giant monster by the nuclear test that damaged their original home",
    "Originally an orphaned cat. They both stole different types of beans in the search of the magic beans. After some time, $NICKNAME gave up stealing things. But their crime buddies, unable to steal without the cat's help, tricked them into a bank robbery. From then on, $NICKNAME became a fugitive from law, searching a way to clear their name",
    "$NICKNAME, a Saiyan baby was sent from Planet Vegeta to Earth to destroy it, but ended up having a nasty bump on the head, which causes them to completely lose their Saiyan characteristics and become an Earthling.",
    "$NICKNAME was the chosen one to fight all that is evil, although they were separated from their parents during war. For a brief period of time, they went down to a darker path until eventually choose to redeem themselves, starting their adventures as a hero.",
    "Originally, Officer Sam Weathers was killed in the line of duty and brought back to life as a crime-fighting cyborg called $NICKNAME"
  ]

  def current_quests
    self.quests.where(completed: false)
  end

  def completed_quests
    self.quests.where(completed: true)
  end

  def completed_quests_xp
    completed_quests.sum(&:xp)
  end

  def bad_guys_xp
    bad_guys.sum(&:total_xp)
  end

  def total_power_ups_xp
    power_ups.sum(&:total_xp)
  end

  def total_xp
    return completed_quests_xp + bad_guys_xp + total_power_ups_xp || 0
  end

  def self.get_random_story(nickname)
    ORIGIN_STORIES.sample.gsub("$NICKNAME", nickname)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @profile = current_user.profile || Profile.new
    @chosen_vision = current_user.profile&.chosen_vision || ChosenVision.new
    @chosen_strategy = ChosenStrategy.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to main_profile_path
    else
      render :new
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to main_profile_path
    else
      render :new
    end
  end

  def fetch_nickname
    name = Faker::Superhero.name
    render json: {name: name }
  end

  def fetch_origin_story
    story = Profile.get_random_story(params[:nickname])
    render json: {story: story }
  end

  private

  def profile_params
    params.require(:profile).permit(:nickname, :secret_bio, :photo)
  end
end

app/views/profiles/_chosen_strategy_form.html.erb
<%= simple_form_for chosen_strategy do |f| %>
  <%= f.input :personal_strategic_goal, hint: "how does #{@profile.nickname} creates adapts the companies strategies ?" %>
  <%= f.association :strategy,label: "⬆️ is an adaptation of:", collection: current_user.company.strategies %>
  <div class="d-flex align-items-center">
    <%= f.button :submit, class: "btn btn-info" %>
    <% if chosen_strategy.id.present? %>
      <i class="ml-2 fas fa-minus clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close edit"> </i>
    <% end %>
  </div>
<% end %>

app/views/profiles/_chosen_vision_form.html.erb
<h3> How does <%= @profile.nickname %> helps the Vision </h3>
<%= simple_form_for @chosen_vision do |f| %>
  <%= f.input :motto,label: "#{@profile.nickname}'s motto is going to be:",placeholder: "with great powers come great responsibilities", hint: "knowing the vision of the company is <b> #{current_user.company.vision.name} </b>, what is your alter-ego motto".html_safe %>
  <div class="d-flex align-items-center">
    <%= f.button :submit, class: "btn btn-info" %>
    <% if @chosen_vision.id.present? %>
      <i class="ml-2 fas fa-minus clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close edit"> </i>
    <% end %>
  </div>
<% end %>

app/views/profiles/_profile_form.html.erb
<%= simple_form_for profile, remote: true do |f| %>
  <div data-controller="fetch-random">
    <%= f.input :nickname, label: "Nickname  <i class='fas fa-pencil-alt clickable' data-action='click->fetch-random#fetch' data-toggle='tooltip' data-url='/fetch_nickname' data-placement='top' title='fetch a random nickname'> </i>".html_safe, placeholder: "Spider-man", input_html: {data: { target: "fetch-random.inputName"} } %>
    <%= f.input :secret_bio, as: :text, label: "Origin Story  <i class='fas fa-pencil-alt clickable' data-action='click->fetch-random#fetchStory' data-toggle='tooltip' data-url='/fetch_origin_story' data-placement='top' title='fetch a random origin story'> </i>".html_safe, placeholder: "As a young man, I was bitten by a radio-active softaware engineered spider. I have at first played with my new powers by making web softwares left and right just for money. But then something really important happened, so I decided to work on my spidey-software skills as to be the best spider-engineer I could think of ", input_html: {data: { target: "fetch-random.inputStory"} } %>
    <%= f.input :photo, as: :file %>

    <div class="d-flex align-items-center">
      <%= f.button :submit, class: "btn btn-primary" %>
      <% if profile.id.present? %>
        <i class="ml-2 fas fa-minus clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close edit"> </i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between w-100">
    <h1> Build your Alter-Ego </h1>
    <% if @profile&.photo&.attached?%>
        <%= cl_image_tag @profile&.photo&.key, class: "avatar-large" %>
      <%else%>
        <%= image_tag "http://icons.iconarchive.com/icons/diversity-avatars/avatars/1024/batman-icon.png", class: "avatar-large" %>
      <%end%>
    <%= link_to "how others see you", profile_path(@profile) if @profile&.chosen_strategies.present? %>
  </div>
  <div data-controller="toggle-display">
    <div data-target="toggle-display.togglable" class="<%= 'd-none' if @profile.id.present? %> ">
      <%= render "profiles/profile_form", profile: @profile %>

    </div>
    <div data-target="toggle-display.togglable" class="card p-2 <%= 'd-none' unless @profile.id.present? %>" >
      <div class="d-flex justify-content-between">
        <h2> <%= @profile.nickname %></h2>
        <i class="fas fa-pencil-alt clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="edit"></i>
      </div>
      <p> <%= @profile.secret_bio %> </p>
    </div>
  </div>
  <% if @profile.id.present? %>
    <div data-controller="toggle-display" class="card mt-2 p-2">
      <div data-target="toggle-display.togglable" class="<%= 'd-none' if @profile.chosen_vision&.id&.present? %> ">
        <%= render 'profiles/chosen_vision_form', chosen_vision: @chosen_vision %>
      </div>
      <div data-target="toggle-display.togglable" class="<%= 'd-none' unless @profile.chosen_vision&.id&.present?  %>" >
        <div class="d-flex justify-content-between">
          <h3> <%= @profile.nickname %> Mission: </h3>
          <i class="fas fa-pencil-alt clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="edit"> </i>
        </div>
            <b> <%= @profile.chosen_vision&.motto %> </b>
      </div>
    </div>
  <% end %>

  <% if @profile.chosen_vision&.id&.present? %>
    <div data-controller="toggle-display" class="card mt-2 p-2">
      <h3> <%= @profile.nickname %> strategies: </h3>

      <div data-target="toggle-display.togglable" class="<%= 'd-none' unless @profile.chosen_strategies.empty? %> ">
        <%= render 'profiles/chosen_strategy_form', chosen_strategy: @chosen_strategy %>
      </div>
      <div data-target="toggle-display.togglable" class="<%= 'd-none' if @profile.chosen_strategies.empty? %> ">
        <ul class="list-group list-group-flush">
          <% @profile.chosen_strategies.each do |strategy| %>
            <div data-controller="toggle-display">

              <li class="list-group-item" data-target="toggle-display.togglable" ><%= strategy.personal_strategic_goal %>
                <i class="fas fa-pencil-alt clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="edit"> </i>
              </li>
              <div data-target="toggle-display.togglable" class="d-none mb-1">
                <%= render 'profiles/chosen_strategy_form', chosen_strategy: strategy %>
              </div>
            </div>
          <% end %>
        </ul>
        <i class="fa fa-plus clickable mt-2" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="Add a strategy"> </i>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 card mr-1 d-flex justify-content-center align-items-center text-center">

      <h1><b><%= @profile.nickname %></b></h1>
      <% if @profile&.photo&.attached?%>
        <%= cl_image_tag @profile&.photo&.key, class: "avatar-large" %>
      <%else%>
        <%= image_tag "http://icons.iconarchive.com/icons/diversity-avatars/avatars/1024/batman-icon.png", class: "avatar-large" %>
      <%end%>
      <p class="text-muted mt-2"><%= @profile.secret_bio  %></p>
      -
      <p class="mt-2"> <strong> <%= @profile.chosen_vision.motto %> </strong> </p>
    </div>
    <div class="col-8 card">
      <div class="list-group list-group-flush">
        <div class="list-group-item">
          <h2>✔ Completed Quests ✔</h2>
          <h3>Total XP: <%= @profile.completed_quests_xp %> XP</h3>
          <% @profile.completed_quests.each do |completed_quest| %>
            <%= render 'dashboard/completed_quest', quest: completed_quest %>
          <% end %>
        </div>

        <div class="list-group-item">
          <h2>📝 Active Quests 📝</h2>
          <% @profile.current_quests.each do |current_quest| %>
            <%= render 'dashboard/active_quest', quest: current_quest %>
          <% end %>
        </div>
       <div class="list-group-item">
          <h2>🤠 Most Wanted Baddies 🤠</h2>
          <h3> Total XP: <%= @profile.bad_guys_xp %> </h3>
          <% @profile.bad_guys.each do |bad_guy| %>
            <%= render 'dashboard/bad_guy', bad_guy: bad_guy %>
          <% end %>
        </div>
        <div class="list-group-item">
          <h2>⭐ Power Ups! ⭐</h2>
          <h3> Total XP: <%= @profile.total_power_ups_xp %></h3>
          <% @profile.power_ups.each do |power_up| %>
            <%= render 'dashboard/power_up', power_up: power_up %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>