config/routes.rb
Rails.application.routes.draw do
  get 'profiles/new'
  devise_for :users
  root to: 'pages#home'
  resources :profiles, except: [:edit]
  get 'fetch_nickname', to: "profiles#fetch_nickname"
  get 'fetch_origin_story', to: "profiles#fetch_origin_story"
  resources :chosen_visions, only: [:create, :update]
  resources :chosen_strategies, only: [:create, :update]
  resources :bad_guys, only: [:create, :update]
  resources :quests, only: [:create, :update]
  resources :power_ups, only: [:create, :update]
  get 'adventures', to: "pages#adventure", as: :adventure
  get 'profile', to: "profiles#new", as: :main_profile

  resources :dashboard, only: :index
  patch "defeat_bad_guy/:id", to: "dashboard#defeat_bad_guy", as: :defeat_bad_guy
  patch "increase_power_up/:id", to: "dashboard#increase_power_up", as: :increase_power_up
  post "change_completion_rate", to: "dashboard#change_completion_rate", as: :change_completion_rate
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad_guy.rb
class BadGuy < ApplicationRecord
  belongs_to :profile
  validates :name, presence: true, uniqueness: { scope: :profile }
  validates :story, presence: true
  validates :xp, presence: true
end

app/models/chosen_strategy.rb
class ChosenStrategy < ApplicationRecord
  belongs_to :profile
  belongs_to :strategy

  has_many :quest_strategies
  has_many :quests, through: :quest_strategies
end

app/models/chosen_vision.rb
class ChosenVision < ApplicationRecord
  belongs_to :profile
  belongs_to :vision

  has_many :power_up_visions
  has_many :power_ups, through: :power_up_visions

  validates :motto, presence: true

end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_one :vision
  has_many :strategies
  has_many :company_bad_guys
  has_many :company_quests
  has_many :company_power_ups

  validates :name, presence: true
end

app/models/company_bad_guy.rb
class CompanyBadGuy < ApplicationRecord
  belongs_to :company
end

app/models/company_power_up.rb
class CompanyPowerUp < ApplicationRecord
  belongs_to :company
end

app/models/company_quest.rb
class CompanyQuest < ApplicationRecord
  belongs_to :company
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/power_up.rb
class PowerUp < ApplicationRecord
  belongs_to :profile

  validates :name, presence: true, uniqueness: { scope: :profile }
  validates :description, presence: true
  validates :xp, presence: true
end

app/models/power_up_vision.rb
class PowerUpVision < ApplicationRecord
  belongs_to :chosen_vision
  belongs_to :power_up
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_one :chosen_vision
  has_many :bad_guys, through: :profile

  has_many :chosen_strategies
  has_many :quests
  has_many :bad_guys
  has_many :power_ups

  validates :nickname, presence: true
  validates :secret_bio, presence: true
  ORIGIN_STORIES = [
    "$NICKNAME had parents murdered by one of the muggers when he was young while walking home from the movies with their parents. Later discovered that their city was plagued by corrupt officials, inspired them to used their vast family fortune to become $NICKNAME and wage a one-person war on crime.",
    "Born on the planet Krypton, infant $NICKNAME was sent to Earth before an explosion destroyed their home planet. Their strong moral code motivates them to fight for justice.",
    "$NICKNAME was once an ordinariy human child, having scientist parents that injected them with reverse evolution serum to save their life from a deadly virus which led to the start of their superhero career.",
    "$NICKNAME was once either an intermediate dinosaur or a prehistoric intermediate reptile who was later transformed into a giant monster by the nuclear test that damaged their original home",
    "Originally an orphaned cat. They both stole different types of beans in the search of the magic beans. After some time, $NICKNAME gave up stealing things. But their crime buddies, unable to steal without the cat's help, tricked them into a bank robbery. From then on, $NICKNAME became a fugitive from law, searching a way to clear their name",
    "$NICKNAME, a Saiyan baby was sent from Planet Vegeta to Earth to destroy it, but ended up having a nasty bump on the head, which causes them to completely lose their Saiyan characteristics and become an Earthling.",
    "$NICKNAME was the chosen one to fight all that is evil, although they were separated from their parents during war. For a brief period of time, they went down to a darker path until eventually choose to redeem themselves, starting their adventures as a hero.",
    "Originally, Officer Sam Weathers was killed in the line of duty and brought back to life as a crime-fighting cyborg called $NICKNAME"
  ]

  def current_quests
    self.quests.where(completed: false)
  end

  def completed_quests
    self.quests.where(completed: true)
  end

  def completed_quests_xp
    completed_quests.sum(&:xp)
  end

  def bad_guys_xp
    bad_guys.sum(&:total_xp)
  end

  def total_power_ups_xp
    power_ups.sum(&:total_xp)
  end

  def total_xp
    return completed_quests_xp + bad_guys_xp + total_power_ups_xp || 0
  end

  def self.get_random_story(nickname)
    ORIGIN_STORIES.sample.gsub("$NICKNAME", nickname)
  end

end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :profile
  has_many :quest_strategies
  has_many :chosen_strategies, through: :quest_strategies
  accepts_nested_attributes_for :quest_strategies

  validates :name, presence: true
  validates :completion_rate, presence: true
  validates :description, presence: true
  validates :xp, presence: true
end

app/models/quest_strategy.rb
class QuestStrategy < ApplicationRecord
  belongs_to :quest
  belongs_to :chosen_strategy
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  belongs_to :company
  has_many :chosen_strategies
  has_many :profiles, through: :chosen_strategies

  validates :name, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :company
  has_one :profile
  before_validation :assign_company
  has_many :memberships
  has_many :teams, through: :memberships

  private

  def assign_company
    self.company ||= Company.last
  end
end

app/models/vision.rb
class Vision < ApplicationRecord
  belongs_to :company
  has_many :chosen_visions
  has_many :profiles, through: :chosen_visions

  validates :name, presence: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def adventure
    @new_bad_guy = BadGuy.new
    @new_power_up = PowerUp.new
    @new_quest = Quest.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adventures/_bad_guy_form.html.erb
<div data-controller="adventure">
  <b> Create a bad guy </b>
  <button type="button" class="btn btn-light btn-small" data-toggle="modal" data-target="#badGuyModal">
    Choose from company's bad guys
  </button>

  <%= simple_form_for bad_guy do |f| %>
    <%= f.input :name, placeholder: "Cigarette Break Man", input_html: { data: { target: "adventure.name"} }%>
    <%= f.input :story, placeholder: "It calls me and force me to spending time destroying my health", input_html: { data: { target: "adventure.story"} } %>
    <%= f.input :xp, hint: "How much XP do you receive everytime you defeat him ? ", input_html: { min: 0, max: 100, data: { target: "adventure.xp"} } %>
    <div class="d-flex align-items-center">
      <%= f.button :submit, class: "btn btn-info" %>
      <% if bad_guy.id.present? %>
          <i class="ml-2 fas fa-pencil-alt clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close edit"> </i>
        <% else %>
          <i class="fa fa-minus clickable ml-2" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close form"> </i>
      <% end %>
    </div>
  <% end %>


  <div class="modal fade" id="badGuyModal" tabindex="-1" aria-labelledby="badGuyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="badGuyModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <b> Select from your Company's known Bad Guys 🤠 </b>
          <select  class="custom-select" name="bad_guy" id="bad_guy" data-action="change->adventure#badGuyChosen">
            <%= current_user.company.company_bad_guys.each do |bad_guy| %>
              <option value="#bad_guy_<%= bad_guy.id%>" id="bad_guy_<%= bad_guy.id%>" data-name="<%= bad_guy.name%>" data-story="<%= bad_guy.story%>" data-xp="<%= bad_guy.xp%>"> <%= bad_guy.name %> </option>
            <% end %>
          </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="d-none" data-target="adventure.adventureBtnModal" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/adventures/_power_up_form.html.erb
<div data-controller="adventure">
  <b> Create a Power-Up </b>
  <button type="button" class="btn btn-light btn-small" data-toggle="modal" data-target="#powerUpModal">
    Choose from company's power ups
  </button>
  <%= simple_form_for power_up do |f| %>
    <%= f.input :name, placeholder: "It's like a pushup: something you don't want to do before, but after you're better and stronger", input_html: { data: { target: "adventure.name"} } %>
    <%= f.input :description, placeholder: "Describe what you would do when you activate this power up", input_html: { data: { target: "adventure.description"} }  %>
    <%= f.input :xp, hint: "How much Xp do you receive whenever you activate it?", input_html: { min: 0, max: 100, data: { target: "adventure.xp"} } %>
    <div class="d-flex align-items-center">
      <%= f.button :submit, class: "btn btn-info" %>
      <% if power_up.id.present? %>
        <i class="ml-2 fas fa-pencil-alt clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close edit"> </i>
      <% else %>
        <i class="fa fa-minus clickable ml-2" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close form"> </i>
      <% end %>
    </div>
  <% end %>

  <div class="modal fade" id="powerUpModal" tabindex="-1" aria-labelledby="powerUpModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="powerUpModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <b> Select from your Company's known Power Ups ⭐ </b>
          <select  class="custom-select" name="power_up" id="power_up" data-action="change->adventure#powerUpChosen">
            <%= current_user.company.company_power_ups.each do |power_up| %>
              <option value="#power_up_<%= power_up.id%>" id="power_up_<%= power_up.id%>" data-name="<%= power_up.name%>" data-description="<%= power_up.description%>" data-xp="<%= power_up.xp%>"> <%= power_up.name %> </option>
            <% end %>
          </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="d-none" data-target="adventure.adventureBtnModal" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/adventures/_quest_form.html.erb
<div data-controller="adventure">
  <b> Create a Quest </b>
  <button type="button" class="btn btn-light btn-small" data-toggle="modal" data-target="#questModal">
    Choose from company's epic quests
  </button>

  <%= simple_form_for quest do |f| %>
    <%= f.input :name, placeholder: "Client hunter", input_html: { data: { target: "adventure.name"} }%>
    <%= f.input :description, as: :text, placeholder: "Try to contact at least 20 new potential clients in 1 week", input_html: { data: { target: "adventure.description"} } %>
    <div id="quest_strategies">
      <%= f.simple_fields_for :quest_strategies do |chosen_strategy| %>
        <%= render 'adventures/quest_strategy_fields', f: chosen_strategy %>
      <% end %>
      <%= link_to_add_association 'Add an associated personnal strategy', f, :quest_strategies, partial: "adventures/quest_strategy_fields" %>
    </div>
    <%= f.input :xp, hint: "How much XP i will earn once i complete the quest ?", input_html: { min: 0, max: 100, data: { target: "adventure.xp"} } %>
    <div class="d-flex align-items-center">
      <%= f.button :submit, class: "btn btn-info" %>
      <% if quest.id.present? %>
       <i class="ml-2 fas fa-pencil-alt clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close edit"> </i>
      <% else %>
        <i class="fa fa-minus clickable ml-2" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="close form"> </i>
      <% end %>
    </div>
  <% end %>

  <div class="modal fade" id="questModal" tabindex="-1" aria-labelledby="questModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="questModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <b> Select from your Company's known Quests 📝 </b>
          <select  class="custom-select" name="quest" id="quest" data-action="change->adventure#questChosen">
            <%= current_user.company.company_quests.each do |quest| %>
              <option value="#quest_<%= quest.id%>" id="quest_<%= quest.id%>" data-name="<%= quest.name%>" data-description="<%= quest.description%>" data-xp="<%= quest.xp%>"> <%= quest.name %> </option>
            <% end %>
          </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="d-none" data-target="adventure.adventureBtnModal" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/adventures/_quest_strategy_fields.html.erb
<div class="nested-fields mb-3">
  <%= f.association :chosen_strategy, collection: current_user.profile.chosen_strategies, label_method: :personal_strategic_goal, value_method: :id %>
  <%= link_to_remove_association "remove associated strategy", f %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SdworxHackathon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <meta name="description" content="We're gamifying employees engagement. Let everybody be the super-hero, let them build their stories and have fun being the best they can">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="Sdworx Engagement" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url("sdworx.png") %>" />
    <meta property="og:description" content="We're gamifying employees engagement. Let everybody be the super-hero, let them build their stories and have fun being the best they can" />
    <meta property="og:site_name" content="SD Engage" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Sdworx Engagement">
    <meta name="twitter:description" content="We're gamifying employees engagement. Let everybody be the super-hero, let them build their stories and have fun being the best they can">
    <meta name="twitter:image:src" content="<%= image_url("sdworx.png") %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/adventure.html.erb
<div class="container">
  <div class="mb-3" data-controller="toggle-display">
    <h3>📝 Quests: </h3>
    <div data-target="toggle-display.togglable" class="<%= 'd-none' unless current_user.profile.quests.empty? %> ">
      <%= render 'adventures/quest_form', quest: @new_quest %>
    </div>
    <div data-target="toggle-display.togglable" class="<%= 'd-none' if current_user.profile.quests.empty? %> ">
      <small>A quest is something you do to bring yourself closer to an epic win for you and the place you work, something that makes you real proud </small>
      <ul class="list-group list-group-flush">
        <% current_user.profile.quests.each do |quest|%>
          <li class="list-group-item"> <%= quest.name %> <%="✔" if quest.completed %> </li>
        <% end %>
      </ul>
       <i class="fa fa-plus clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="Add a quest"> </i>
    </div>
  </div>
  <div class="mb-3" data-controller="toggle-display">
    <h3>⭐ Power Ups: </h3>
    <div data-target="toggle-display.togglable" class="<%= 'd-none' unless current_user.profile.power_ups.empty? %> ">
      <%= render 'adventures/power_up_form', power_up: @new_power_up %>
    </div>
    <div data-target="toggle-display.togglable" class="<%= 'd-none' if current_user.profile.power_ups.empty? %> ">
      <small>Power-ups are things that are easy to do, and make you feel good, but you don't always do. Think of them like a push-up </small>
      <ul class="list-group list-group-flush">
        <% current_user.profile.power_ups.each do |power_up|%>
          <li class="list-group-item"> <%= power_up.name %> </li>
        <% end %>
      </ul>
       <i class="fa fa-plus clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="Add a power_up"> </i>
    </div>
  </div>
  <div class="mb-3" data-controller="toggle-display">
    <h3>🤠 Bad Guys: </h3>
    <small>Your bad guys are the ways you keep yourself from your goals </small>
    <div data-target="toggle-display.togglable" class="<%= 'd-none' unless current_user.profile.bad_guys.empty? %> ">
      <%= render 'adventures/bad_guy_form', bad_guy: @new_bad_guy %>
    </div>
    <div data-target="toggle-display.togglable" class="<%= 'd-none' if current_user.profile.bad_guys.empty? %> ">
      <ul class="list-group list-group-flush">
        <% current_user.profile.bad_guys.each do |bad_guy|%>
          <li class="list-group-item"> <%= bad_guy.name %> </li>
        <% end %>
      </ul>
       <i class="fa fa-plus clickable" data-action="click->toggle-display#toggleDiv" data-toggle="tooltip" data-placement="top" title="Add a bad guy"> </i>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>SD-Engage</h1>
  <h2> gamifying employees engagement </h2>
  <p>
    Gamifying is one of the <%= link_to "https://www.iftf.org/fileadmin/user_upload/downloads/books/BobJohansen_QA-NewLeadershipLiteracies.pdf", target: :blank do %>  literacies of future leaders <% end %>
  </p>
  <p>
    Hence, this app looks at incorporating games as a way to augment employee engagement
  </p>
  <p>
    This app is inspired by two books:
    <ul>
      <li><%= link_to "https://en.wikipedia.org/wiki/Start_with_Why", target: :blank do %> <em>Start with Why (2009) </em> by <b> Simon Sinek </b> <% end %> </li>
      <li><%= link_to "https://www.goodreads.com/book/show/24611964-superbetter", target: :blank do %> <em>SuperBetter (2015) </em> by <b>  Jane McGonigal
 </b> <% end %> </li>
    </ul>
  </p>

  <p>
    The first book gave us the foundation for finding where employee engagement comes from
  </p>
  <p>
    The second taught us, and proved by research, how to gamify the foundations of engagement
  </p>

  <p> The main idea is to accompany the employee in the development of her/his psychological strength with the help of his company </p>

  <p> we help employees doing so by having employees:
    <ul>
      <li> creating a secret identity as to increase self-efficacy</li>
      <li> developping a sense of purpose by creating and completing quests </li>
      <li> collecting and activating power ups to develop better emotional control </li>
      <li> finding and battling bad guys as to increase mental flexibility </li>
      <li> all in all challenge themselves and adopt challenge mindset </li>
    </ul>
  </p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-sdworx">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "sdworx.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item <%= 'active' if params[:controller] == 'dashboard' %> ">
        <%= link_to "Dashboard", dashboard_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if params[:action] == 'adventure' %>">
        <%= link_to "New Adventures", adventure_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if params[:controller] == 'profiles' %>">
        <%= link_to "My Profile", main_profile_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.profile&.photo&.attached?%>
          <%= cl_image_tag current_user.profile&.photo&.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
        <%else%>
          <%= image_tag "http://icons.iconarchive.com/icons/diversity-avatars/avatars/1024/batman-icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%end%>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>